name: cod_morse
description: Morse Converter
publish_to: 'none'
version: 5.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.4
  flutter_localizations:
    sdk: flutter
  torch_light: ^1.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
